name: Login Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'login_test/**'
      - '.github/workflows/login_test.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'login_test/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Chrome and ChromeDriver
        run: |
             wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
             sudo dpkg -i google-chrome-stable_current_amd64.deb
             sudo apt-get update
             sudo apt-get install -f
             CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
             CHROMEDRIVER_VERSION=$(echo $CHROME_VERSION | sed 's/\.[0-9]*$//')
             wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
             unzip chromedriver_linux64.zip
             sudo mv chromedriver /usr/local/bin/
             sudo chown root:root /usr/local/bin/chromedriver
             sudo chmod +x /usr/local/bin/chromedriver

      - name: Check directory structure
        run: |
          pwd
          ls -la
          ls -la login_test || echo "login_test directory not found"

      - name: Build and test with Maven
        working-directory: ./login_test
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          mvn clean test -X \
            -DADMIN_USERNAME='${{ secrets.ADMIN_USERNAME }}' \
            -DADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}' \
            -DBASE_URL='${{ secrets.BASE_URL }}'
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: login_test/target/surefire-reports
