name: Login Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'login_test/**'
      - '.github/workflows/login_test.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'login_test/**'
  workflow_dispatch:  # Дозволяє запускати workflow вручну

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build and test with Maven
        working-directory: ./login_test
        run: |
          mvn clean test \
            -DADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
            -DADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            -DBASE_URL=${{ secrets.BASE_URL }}

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: login_test/target/surefire-reports
